language: java

jdk:
 - openjdk6

before_install: 
 - sudo apt-get update -qq
 - sudo apt-get install -y ant
 - sudo apt-get install -y ecj
 - env

# Get the ecj.jar
 - wget http://grid.ct.infn.it/statistics/ecj.jar
 - sudo cp ecj.jar /usr/share/ant/lib/

# Building the servlet 
install:
 - cd eTokenServer
 - ant test
 - cd eTokenUtils
 - ant test
 - cd MyProxyServer
 - ant test

notifications:
  email:
    recipients:
        - giuseppe.larocca@ct.infn.it
